마감하기 - 판매, 재고, 고장 조회 및 재고등록
EZ-Korea-corp/ez_korea_app pull request #10
Opened 2023-02-01 13:53 UTC by gkraud4135

##판매, 재고, 고장 조회
###판매 조회
오늘 내가 판 와이퍼에대한 갯수 통계
###고장 조회
오늘 고장난 와이퍼 갯수 통계
###재고 조회
--------------------------------------------------------
    어제 마감 기준 등록된 재고
(+) 총 입고 갯수 (오늘 내가 일하고 있는 주유소의)
(-)  총 판매 갯수 (오늘 내가 일하고 있는 주유소의)
(-)  총 고장 갯수 (오늘 내가 일하고 있는 주유소의)
--------------------------------------------------------
![20230131_235606](https://user-images.githubusercontent.com/77388722/216056775-fce91453-7817-465b-b718-42d6f2fda512.png)
![20230131_235610](https://user-images.githubusercontent.com/77388722/216056786-1b27b7a4-7d53-411f-9afa-727dccd5e480.png)
![20230131_235614](https://user-images.githubusercontent.com/77388722/216056790-5c3a9f2c-d730-4d87-bc7c-81d3c13d0f8e.png)

##재고등록
###마감하기 - 재고 조회탭에서만 마감하기 버튼 활성화(재고 갯수 확인 각인)
여러명이서 등록하더라도 재고 데이터는 곧 주유소의 현황으로 여러명이 마감하면 마지막인원의 마감이 최종 마감이된다
(마감은 주유소별 1개의 데이터만 가진다)

### 개선사항
1. 현재는 하루에 1개만 dailyTask가 등록된다는 가정하에 만들어져있음 > 
만약 하루에 두개가 등록되면 `findByMemberAndDate()` 의 결과는 2개가 나오게 되고 오류가된다
추후 변경한다면 ORDER BY 최신순 마지막 1개로 조회하면 될것같다. (마감 조회 페이지도 이에 맞게 설계)
2. 필요시 saleProduct테이블 판매 데이터 데이터 마이그레이션 진행예정
등록중에는 row가 필요하기 때문에 분할되어야하지만 마감 이후엔 갯수가 중요하므로 마감시 할 예정
[전]                              
| id  | 갯수 | 상태 | 
| ---|---|--- |
| 1  | 1 | 판매 | 
| 1  | 1 | 판매 |

[후]
| id  | 갯수 | 상태 | 
| ---|---|--- |
| 1  | 2 | 판매 |
3. 판매, 입고, 고장 기록은 추후 엑셀로 다운 가능하게 만들것이고 다운받아 추후 문제 발생시 과거 데이터 확인을 직접 확인하게 교육 할 예정
4. saleProduct 데이터는 정산등록시 정산일자 이전 데이터는 필요없는 데이터로 삭제할예정

2023-02-01 15:06 UTC, Jwhyee requested changes
역시 마이바티스가 들어가니까 날아다니는구만 수고했슈~!

2023-02-01 15:06 UTC, Jwhyee commented on src/main/java/com/ezkorea/hybrid_app/service/sales/SaleService.java
> +        paramMap.put("status", "stock");
여기도 문자열은 상수로 변경하는게 좋을 것 같아!

2023-02-01 15:06 UTC, Jwhyee commented on src/main/resources/templates/sales/close-detail.html
> +                    $form.find("span[name=" + item.wiper + "]").text(item.count);
오 테이블에 뿌리는게 `html` 코드를 넣어서 뿌리는게 아니라 찾아서 값만 지정해주는거였구나.. 처음알았어..

2023-02-04 12:03 UTC, gkraud4135 commented on src/main/java/com/ezkorea/hybrid_app/app/util/Ut.java
> +    public static String dateToString(LocalDate date, String _format) {
파라미터로 쓰려고 했던건데 안써서 삭제했어!

2023-02-04 13:24 UTC, gkraud4135 commented on src/main/java/com/ezkorea/hybrid_app/app/util/Ut.java
> -    }
안쓰는 메서드 삭제

2023-02-04 13:24 UTC, gkraud4135 commented on src/main/java/com/ezkorea/hybrid_app/domain/sale/SaleStatus.java
> +
saleProduct status 상수로 관리

2023-02-04 13:24 UTC, gkraud4135 commented on src/main/resources/mapper/saleProduct.xml
>          SELECT    A.WIPER_ID AS WIPER
재고 = 오늘 주유소의 총(입고 - 출고 - 고장) + 마지막으로 등록된 날짜의 재고

2023-02-04 16:42 UTC, Jwhyee commented on src/main/java/com/ezkorea/hybrid_app/domain/sale/SaleStatus.java
> +
굿 사용 반경이 한정적이라면 `Enum`이 아니라 `final`로 선언한 상수가 더 좋을 때도 있어!
요 차이는 한 번 확인해보면 좋을듯!

2023-02-04 16:42 UTC, Jwhyee commented on src/main/resources/mapper/saleProduct.xml
>          SELECT    A.WIPER_ID AS WIPER
굿굿 수고했으!

2023-02-04 16:43 UTC, Jwhyee submitted a review, later dismissed
develop으로 올려도 좋을 것 같아! 수고했어!
앞으로 어떤걸 해야할지 방향을 잡고 그거에 맞게 개발하는게 좋을 것 같댜
다음 주 중으로 한 번 만나던가 디코 통해서 회의 한 번 해보자!!

2023-02-05 13:44 UTC, gkraud4135 commented on src/main/java/com/ezkorea/hybrid_app/domain/sale/SaleStatus.java
> +
아 final 상수를 말했던거였구나 ㅋㅋㅋ

2023-02-05 15:27 UTC, Jwhyee approved these changes
리뷰한 내용만 수정하면 머지해도 될듯!

2023-02-05 15:27 UTC, Jwhyee commented on src/main/java/com/ezkorea/hybrid_app/service/sales/GasStationService.java
> +        return station.get();
이 부분은 가능하면 `.get()`보다는 `.orElseThrow()`로 사용하는게 좋을 것 같아!
`null`이 반환되면 플로우가 자연스럽지 않게 되니까 `ExceptionHandler`를 탈 수 있도록 수정해줘!!`memberService` 쪽에 비슷한 코드 있을거야!

2023-02-06 11:33 UTC, gkraud4135 commented on src/main/java/com/ezkorea/hybrid_app/service/sales/GasStationService.java
> +        return station.get();
이부분이 궁금한게 있는데 만약 특정 `ExceptionHandler`에 파라미터를 전달할수있어?

예를들어 id가 1인 member의 친구목록을 가져왔는데 없으면 해당 멤버 페이지로 다시 넘어가게 memeber/detail/1로 넘어가고싶은데 1을 어떻게 전달해야하나 싶어서

2023-02-06 11:33 UTC, merged